export const mockChinguData = [
  {
    id: "1",
    timestamp: "2023-10-15T14:30:00Z",
    gender: "Female",
    country: "United States",
    roleType: "Developer",
    role: "Frontend",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 3",
    voyage: "Voyage 46",
  },
  {
    id: "2",
    timestamp: "2023-09-12T09:15:00Z",
    gender: "Male",
    country: "United Kingdom",
    roleType: "Developer",
    role: "Backend",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 2",
    voyage: "Voyage 45",
  },
  {
    id: "3",
    timestamp: "2023-11-01T10:00:00Z",
    gender: "Non-binary",
    country: "Canada",
    roleType: "Designer",
    role: "UI/UX",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 1",
    voyage: "Voyage 47",
  },
  {
    id: "4",
    timestamp: "2022-05-20T16:45:00Z",
    gender: "Female",
    country: "Nigeria",
    roleType: "Developer",
    role: "Fullstack",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 3",
    voyage: "Voyage 44",
  },
  {
    id: "5",
    timestamp: "2023-01-10T08:20:00Z",
    gender: "Male",
    country: "Germany",
    roleType: "Data Scientist",
    role: "Data Analyst",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 2",
    voyage: "Voyage 43",
  },
  {
    id: "6",
    timestamp: "2023-08-05T11:30:00Z",
    gender: "Female",
    country: "India",
    roleType: "Developer",
    role: "Frontend",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 1",
    voyage: "Voyage 46",
  },
  {
    id: "7",
    timestamp: "2023-10-25T13:10:00Z",
    gender: "Male",
    country: "Brazil",
    roleType: "Developer",
    role: "Backend",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 2",
    voyage: "Voyage 47",
  },
  {
    id: "8",
    timestamp: "2021-12-15T15:00:00Z",
    gender: "Prefer not to say",
    country: "Australia",
    roleType: "Product Manager",
    role: "PM",
    soloProjectTier: "N/A",
    voyageTier: "Tier 3",
    voyage: "Voyage 39",
  },
  {
    id: "9",
    timestamp: "2023-07-07T09:45:00Z",
    gender: "Female",
    country: "Kenya",
    roleType: "Developer",
    role: "Fullstack",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 3",
    voyage: "Voyage 45",
  },
  {
    id: "10",
    timestamp: "2023-02-14T10:30:00Z",
    gender: "Male",
    country: "Japan",
    roleType: "Designer",
    role: "Graphic Designer",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 1",
    voyage: "Voyage 42",
  },
  {
    id: "11",
    timestamp: "2023-11-20T14:15:00Z",
    gender: "Male",
    country: "United States",
    roleType: "Developer",
    role: "Frontend",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 2",
    voyage: "Voyage 47",
  },
  {
    id: "12",
    timestamp: "2023-06-30T11:00:00Z",
    gender: "Female",
    country: "France",
    roleType: "Developer",
    role: "Backend",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 3",
    voyage: "Voyage 44",
  },
];

export const getUniqueValues = (key) => {
  const values = mockChinguData.map((item) => item[key] || "");
  return Array.from(new Set(values.filter(Boolean))).sort();
};

export const getYears = () => {
  const years = mockChinguData.map((item) =>
    new Date(item.timestamp).getFullYear().toString()
  );
  return Array.from(new Set(years)).sort().reverse();
};
